config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  get 'news', to: 'posts#index'
  get 'profile', to: 'pages#profile'
  get 'schedule', to: 'pages#schedule'

  devise_for :users
  resources :homeworks, only: %i[index create update]
  resources :lessons, only: %i[index update]
  resources :lesson_works, only: :update

  devise_for :admin_users, ActiveAdmin::Devise.config
  namespace :admin do
    get 'students/import', to: 'students#import'
    post 'students/import_file', to: 'students#import_file'
  end
  ActiveAdmin.routes(self)
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :students
end

app/models/homework.rb
class Homework < ApplicationRecord
  belongs_to :group
  belongs_to :subject
  belongs_to :lesson

  has_one_attached :file
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :subject
  belongs_to :group
  belongs_to :user, optional: true
  has_one :homework
end

app/models/lesson_work.rb
class LessonWork < ApplicationRecord
  belongs_to :student
  belongs_to :lesson
  enum present: {
    yes: 0,
    past: 1,
    no: 2
  }
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :group
  has_many :lesson_works
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :homeworks
  has_many :subjects
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :lessons
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_out_path_for(_)
    new_user_session_path
  end
end

app/controllers/homeworks_controller.rb
class HomeworksController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = Group.all
    @group = Group.find_by(id: params[:group_id]) || @groups.first
    @students = @group.students
    @subjects = Subject.all
    @subject = Group.find_by(id: params[:subject_id]) || @subjects.first
    @lessons = Lesson.where(group: @group, subject: @subject)
    # @homeworks = Homework.where(group: @group, subject: @subject)
  end

  def create
    @homework = Homework.create(homework_params)
    respond_to do |format|
      format.turbo_stream
    end
  end

  def update
    homework.update(homework_params)
    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def homework
    @homework ||= Homework.find(params[:id])
  end

  def homework_params
    params.require(:homework).permit(:lesson_id,:subject_id,:file,:group_id)
  end
end

app/controllers/lesson_works_controller.rb
class LessonWorksController < ApplicationController
  def update
    lesson_work.update(lesson_work_params)
    respond_to do |format|
      format.turbo_stream
      format.html {return }
    end
  end

  private

  def lesson_work
    @lesson_work ||= LessonWork.find(params[:id])
  end

  def lesson_work_params
    params.require(:lesson_work).permit(:score,:present,:comment)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!

  def index
    @day = Date.current
    @lessons = current_user.lessons.where(event_at: @day)
  end

  def update
    lesson.update(lesson_params)
    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def lesson
    @lesson ||= Lesson.find(params[:id])
  end

  def lesson_params
    params.require(:lesson).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!

  def home
  end

  def profile
    @user = current_user
    group_ids = @user.lessons.map(&:group_id)
    @groups = Group.where(id: group_ids)
  end

  def schedule
    date =  ((Date.parse(params[:date]) if params[:date] )|| Date.current).beginning_of_week
    @beginning_of_week = date
    @prev_week =  @beginning_of_week-1.day
    @end_of_week = date.end_of_week
    @next_week = @end_of_week+1.day
    @lessons = current_user.lessons.where("event_at >= ? AND event_at <= ?",@beginning_of_week, @end_of_week)
    @day = date
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @posts = Post.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lesson_works_helper.rb
module LessonWorksHelper
end

app/views/admin/students/import.html.erb
<%= form_tag admin_students_import_file_path, multipart: true, method: :post do %>
  <div class="">
    <%= file_field_tag :file %>
  </div>
  <div class="">
    <%= submit_tag :import %>
  </div>
<% end %>

app/views/homeworks/_form.html.erb
<div id="<%="#{dom_id(homework.lesson)}_modal"%>">
  <button type="button" class="btn btn__primary btn__auto w-100" data-bs-toggle="modal" data-bs-target="#staticBackdrop<%=homework.lesson_id%>">
    Добавити завдання
  </button>
  <!-- Modal -->
  <div class="modal fade" id="staticBackdrop<%=homework.lesson_id%>" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <%= form_for homework, id: "#{dom_id(homework)}_form" do |form| %>
          <div class="modal-header">
            <h5 class="modal-title text-center" id="staticBackdropLabel">Добавити завдання</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <%= form.hidden_field :lesson_id %>
            <%= form.hidden_field :group_id, value: homework.lesson.group_id %>
            <%= form.hidden_field :subject_id, value: homework.lesson.subject_id %>
            <%= form.file_field :file, class: "input_file" %>
            <%= form.label :file, class: "btn btn__auto w-100" do%>
            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-upload" viewBox="0 0 16 16">
              <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
              <path d="M7.646 1.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 2.707V11.5a.5.5 0 0 1-1 0V2.707L5.354 4.854a.5.5 0 1 1-.708-.708l3-3z"/>
            </svg>
              <span>Вибрати файл</span>
            <%end%>
            <%= link_to "Прикріплений файл", url_for(homework.file), target:"_blank", class: "d-block text-center mt-3" if !homework.new_record? && homework.file.attached? %>
          </div>
          <div class="modal-footer">
            <%= form.submit "Добавити завдання", class:"btn btn__primary btn__auto w-100", data: { bs_dismiss: "modal"} %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
  var inputs = document.querySelectorAll( '.input_file' );
    Array.prototype.forEach.call( inputs, function( input )
    {
      var label	 = input.nextElementSibling,
        labelVal = label.innerHTML;

      input.addEventListener( 'change', function( e )
      {
        var fileName = '';
        fileName = e.target.value.split( '\\' ).pop();
        if( fileName )
          label.querySelector( 'span' ).innerHTML = fileName;
        else
          label.innerHTML = labelVal;
      });
    });
</script>

app/views/homeworks/_student.html.erb
<tr>
  <td><%=index+1%></td>
  <td><%=student.name%></td>
  <td class="text-center"><%=student.lesson_works.average(:score)%></td>
  <%lessons.each do |lesson|%>
    <% if lesson.homework%>
      <td class="text-center">-</td>
    <%end%>
  <%end%>
</tr>

app/views/homeworks/create.turbo_stream.erb
<%= turbo_stream.replace "#{dom_id(@homework.lesson)}_modal" do %>
  <%= render 'form', homework: @homework %>
<% end %>

app/views/homeworks/index.html.erb
<h1 class="text-center">Перевірити завдання</h1>
<div class="mb-3">
  <%= form_with url: homeworks_path, method: :get, class:"d-flex" do |form| %>
    <div class="form-floating me-3">
      <%= form.select :group_id, options_from_collection_for_select(@groups, "id", "name",@group.id), {}, {class: "form-select"} %>
      <%= form.label :group_id, "Група"%>
    </div>
    <div class="form-floating me-3">
      <%= form.select :subject_id, options_from_collection_for_select(@subjects, "id", "name",@subject.id), {}, {class: "form-select"} %>
      <%= form.label :subject_id, "Предмет"%>
    </div>
    <%= form.submit "Показати", class: "btn btn__outline btn__auto" %>
  <% end %>
</div>
<div class="table-responsive">
  <table class="table">
    <tr>
      <th>#</th>
      <th>Студент</th>
      <th class="text-center">
        Середній бал
      </th>
      <%@lessons.each do |lesson|%>
        <% if lesson.homework%>
        <th class="text-center"><%=lesson.name%></th>
        <%end%>
      <%end%>
    </tr>
    <% @students.each_with_index do |student, index|%>
      <%= render "student", student: student, index: index, lessons: @lessons%>
    <%end%>
  </table>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg mb-5">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to root_path, class:"navbar-brand"  do %>
      TB
    <%end%>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to lessons_path, class:"nav-link #{'nav-link__active' if current_page?(lessons_path)}"  do %>
            Присутні
          <%end%>
        </li>
        <li class="nav-item">
          <%= link_to schedule_path, class:"nav-link #{'nav-link__active' if current_page?(schedule_path)}"  do %>
            Розклад
          <%end%>
        </li>
        <li class="nav-item">
          <%= link_to homeworks_path, class:"nav-link #{'nav-link__active' if current_page?(homeworks_path)}"  do %>
            Перевірити завдання
          <%end%>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to news_path, class:"nav-link me-3 #{'nav-link__active' if current_page?(news_path)}", title: "Новини"  do %>
          <i class="fa-solid fa-bell fa-xl"></i>
          <span class="d-lg-none">Новини</span>
          <%end%>
        </li>
        <li class="nav-item">
          <%= link_to profile_path, class:"nav-link me-3 #{'nav-link__active' if current_page?(profile_path)}", title: "Профіль"  do %>
            <i class="fa-solid fa-user fa-xl"></i>
            <span class="d-lg-none">Профіль</span>
          <%end%>
        </li>
        <li class="nav-item">
          <%= link_to destroy_user_session_path, method: :delete,class:"nav-link", title: "Вихід", target: "_top"  do %>
            <i class="fa-solid fa-arrow-right-from-bracket fa-xl"></i>
            <span class="d-lg-none">Вихід</span>
          <%end%>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeachersOffice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://kit.fontawesome.com/6d8be4ff65.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeachersOffice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/lesson_works/_form.html.erb
<%= form_with model: lesson_work, id:"#{dom_id(lesson_work)}_form", class:"lesson_work_form" do |f|%>
  <div class="row mx-0 align-items-center">
    <div class="col-3 text-center">
      <%=lesson_work.student.name%>
    </div>
    <div class="col-3 text-center">
      <div class="field d-inline-block mx-2">
        <%= f.radio_button :present, "yes", class:"custom_radio radio_green", id:"present_#{lesson_work.id}_yes",onchange:"this.form.requestSubmit()"%>
        <label for="present_<%= lesson_work.id%>_yes" title="Присутній"></label>
      </div>
      <div class="field d-inline-block mx-2">
        <%= f.radio_button :present, "past", class: "custom_radio radio_yellow", id:"present_#{lesson_work.id}_past",onchange:"this.form.requestSubmit()"%>
        <label for="present_<%= lesson_work.id%>_past" title="Запізнився"></label>
      </div>
      <div class="field d-inline-block mx-2">
        <%= f.radio_button :present, "no", class:"custom_radio radio_red", id: "present_#{lesson_work.id}_no",onchange:"this.form.requestSubmit()"%>
        <label for="present_<%= lesson_work.id%>_no" title="Відсутній"></label>
      </div>
    </div>
    <div class="col-2 text-center">
      <%=f.select :score, (1..5).to_a, {selected: f.object.score},{class:"form-select form-select-lg w-auto mx-auto", onchange:"this.form.requestSubmit()"}%>
    </div>
    <div class="col-4 text-center">
      <%=f.text_area :comment, class:"form-control", rows: 2, onchange:"this.form.requestSubmit()" %>
    </div>
  </div>
<%end%>

app/views/lesson_works/_lesson_work.html.erb
  <%= render "lesson_works/form", lesson_work: lesson_work, index: index%>

app/views/lesson_works/update.turbo_stream.erb
<%= turbo_stream.replace "#{dom_id(@lesson_work)}_form" do %>
  <%= render 'form', lesson_work: @lesson_work %>
<% end %>
  

app/views/lessons/_form.html.erb
<%= form_for lesson do |form| %>
  <div class="row align-items-center">
    <div class="col-9">
      <div class="form-floating">
        <%= form.text_field :name, class:"form-control", autofocus: true, autocomplete: "name", placeholder: "name@example.com" %>
        <label for="lesson_name">Назва заняття</label>
      </div>

    </div>
    <div class="col-3">
      <%= form.submit "Оновити", class: "btn btn__outline btn__auto"%>
    </div>
  </div>
<% end %>

app/views/lessons/index.html.erb
<h1 class="text-center"><%=@day.strftime("%e %B, %Y")%></h1>
<div class="nav nav-tabs" id="nav-tab" role="tablist">
  <%8.times do |i|%>
    <%i +=1%>
    <% lesson = @lessons.where(number: i).first %>
    <% if lesson%>
      <button class="nav-link" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#lesson_<%=i%>" type="button" role="tab" aria-controls="lesson_<%=i%>">Пара <%= i%></button>
    <% else %>
      <button class="nav-link disabled" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#lesson_<%=i%>" type="button" role="tab" aria-controls="lesson_<%=i%>" disabled>Пара <%= i%></button>
    <%end%>
  <%end%>
</div>
<div class="tab-content" id="myTabContent">
  <% @lessons.each do |lesson| %>
    <% group = lesson.group%>
    <div class="tab-pane fade" id="lesson_<%=lesson.number%>" role="tabpanel">
      <div class="row my-3 align-items-center justify-content-between">
        <div class="col-12 col-md-6 col-xl-2">
          <small class="color_gray d-block mb-1">Група:</small> </b> <%= lesson.group.name%>
      </div>
      <div class="col-12 col-md-6 col-xl-2">
        <small class="color_gray d-block mb-1">Предмет:</small>  <%= lesson.subject.name%>
      </div>
      <div class="col-12 col-md-6 col-xl-5">
        <%=render "form", lesson: lesson %>
      </div>
      <div class="col-12 col-md-6 col-xl-3 text-end">
        <%= render "homeworks/form", homework: (lesson.homework || lesson.build_homework) %>
      </div>
    </div>
    <div class="row-responsive mt-4">
      <div class="row mx-0 fw-bold my-1">
        <div class="col-1 text-center">
          #
        </div>
        <div class="col-11">
          <div class="row mx-0 align-items-center">
            <div class="col-3 text-center">
              Прізвище, ім'я
            </div>
            <div class="col-3 text-center">
              Присутній
            </div>
            <div class="col-2 text-center">
              Оцінка
            </div>
            <div class="col-4 text-center">
              Коментар
            </div>
          </div>
        </div>
        <div class="col-12"><hr></div>
      </div>  
      <div class="row mx-0 align-items-center">
        <% group.students.each_with_index do |student, index|%>
          <div class="col-md-1 text-center ьи">
            <%=index+1%>
          </div>
          <div class="col-11">
            <%= render "lesson_works/lesson_work", lesson_work: LessonWork.find_or_create_by!(student: student, lesson: lesson), index:index %>
          </div>
          <div class="col-12"><hr></div>
        <%end%>
      </div>

    </div>
  </div>
<%end%>
</div>

app/views/pages/home.html.erb
<h1 class="text-center">HOME</h1>

app/views/pages/profile.html.erb
<h1 class="text-center">Профіль</h1>
<h6 class="row"><small class="col-3 text-end fw-light">ПІБ:</small><%= current_user.name%></h6>
<h6 class="row"><small class="col-3 text-end fw-light">Електронна адреса:</small><%= current_user.email%></h6>
<h6 class="row"> <small class="col-3 text-end fw-light">Групи:</small>
    <div class="col-9">
        <% @groups.each do |group|%>
            <span class="fw-light"><%=group.name%></span><br>
        <%end%>
    </div>
</h6>

app/views/pages/schedule.html.erb
<h1 class="text-center">Розклад</h1>
<div class="text-center my-3">
  <%=link_to "<- Попередній ", schedule_path(date: @prev_week)%>
  <b><%= @beginning_of_week.day%>-<%= @end_of_week.day%> <%=@end_of_week.strftime('%B %Y')%></b>
  <%=link_to " Наступний ->", schedule_path(date: @next_week)%>
</div>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th></th>
        <th class="text-center">8:00 - 9:35</th>
        <th class="text-center">9:55 - 11:30</th>
        <th class="text-center">12:00 - 13:35</th>
        <th class="text-center">13:55 - 15:15</th>
        <th class="text-center">15:25 - 16:45</th>
        <th class="text-center">16:55 - 18:15</th>
        <th class="text-center">18:25 - 19:45</th>
        <th class="text-center">19:55 - 21:15</th>
      </tr>
    </thead>
    <tbody>
      <% (0..6).each do %>
        <tr>
          <td class="fw-bold"><%=@day.strftime("%a")%></td>
          <% (1..8).each do |j|%>
            <td class="text-center">
              <% @lessons.where(number: j, event_at: @day).each do |lesson|%>
                <%= lesson.subject.name%>
                <br>
                <small>(<%= lesson.group.name%>)</small>
              <% end %>
            </td>
          <%end%>
          <% @day = @day.tomorrow%>
        </tr>
      <%end%>
    </tbody>
  </table>
</div>

app/views/posts/_post.html.erb
<div class="col-12 col-md-4 mb-3">
  <div class="Box Box__card Box__radius" title="Дізнатись більше" data-bs-toggle="modal" data-bs-target="#newsModal" data-bs-modalTitle="<%= post.name %>" data-bs-modalDesc="<%= post.text %>">
    <%=image_tag post.image, class: "Box__photo"%>
    <div class="p-2">
      <h3 class="h5 mt-1" title="<%= post.name %>"><%=post.name.truncate(40)%></h3>
      <p class="m-0"><%=post.text.truncate(80)%></p>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<h1 class="text-center">Новини</h1>
<div class="row">
  <%= render @posts %>
</div>

<div class="modal fade" id="newsModal" tabindex="-1" aria-labelledby="newsModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content Box Box__radius">
      <div class="modal-header align-items-center justify-content-center">
        <h5 class="modal-title modal__title text-center h6 mb-0" id="newsModalLabel">New message</h5>
      </div>
      <div class="modal-body">
        <p class="modal__text"></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрити</button>
      </div>
    </div>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Увійти", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Забули пароль?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>